import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const U=Deno.env.get("SUPABASE_URL")??"",S=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"";
const db=createClient(U,S,{auth:{persistSession:false,autoRefreshToken:false}});
const subjects=["语文","数学","英语","物理","化学","生物","历史","地理","政治"];
const subjectMax:Record<string,number>={"语文":150,"数学":150,"英语":150,"物理":100,"化学":100,"生物":100,"历史":100,"地理":100,"政治":100};
const adjectives=["bright","calm","clever","fresh","happy","kind","lucky","neat","quick","sunny"],nouns=["panda","fox","kite","maple","river","star","cloud","leaf","moon","pine"];
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const out=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{...cors,"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}});
const rb=(n:number)=>{const a=new Uint8Array(n);crypto.getRandomValues(a);return a},ri=(max:number)=>{const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]%max};
const b64=(a:Uint8Array)=>{let s="";for(const b of a)s+=String.fromCharCode(b);return btoa(s)},unb64=(s:string)=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
const username=()=>`${adjectives[ri(adjectives.length)]}-${nouns[ri(nouns.length)]}-${String(ri(10000)).padStart(4,"0")}`,password=()=>Array.from({length:10},()=>String(ri(10))).join("");
async function sha(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,"0")).join("")}
async function hashPassword(p:string,salt?:Uint8Array){const s=salt??rb(16),k=await crypto.subtle.importKey("raw",new TextEncoder().encode(p),{name:"PBKDF2"},false,["deriveBits"]),bits=await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt:s,iterations:150000},k,256);return{hash:b64(new Uint8Array(bits)),salt:b64(s)}}
async function session(userId:string){const raw=b64(rb(32)).replaceAll("+","-").replaceAll("/","_").replaceAll("=",""),h=await sha(raw),expires=new Date(Date.now()+180*86400000).toISOString();const {error}=await db.from("score_tracker_users").update({session_token_hash:h,session_expires_at:expires,updated_at:new Date().toISOString()}).eq("id",userId);if(error)throw error;return raw}
async function auth(token:string){if(!token)return null;const {data}=await db.from("score_tracker_users").select("id,username,is_admin,session_expires_at,created_at").eq("session_token_hash",await sha(token)).maybeSingle();if(!data||!data.session_expires_at||new Date(data.session_expires_at).getTime()<Date.now())return null;return data}
const clean=(v:unknown)=>{if(v===null||v===undefined||v==="")return null;const x=Number(v);return Number.isFinite(x)&&x>=0&&x<=999?Math.round(x*100)/100:null};
const txt=(v:unknown,n=200)=>typeof v==='string'&&v.trim()?v.trim().slice(0,n):null;
const uuid=(v:unknown)=>typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v)?v:null;
const ipFrom=(req:Request)=>txt(req.headers.get('x-score-client-ip')||req.headers.get('cf-connecting-ip')||req.headers.get('x-forwarded-for')?.split(',')[0]||req.headers.get('x-real-ip'),80);
const isPublicIp=(ip:string|null)=>!!ip&&!/^(127\.|10\.|192\.168\.|172\.(1[6-9]|2\d|3[01])\.|0\.|169\.254\.|::1$|fc|fd|fe80)/i.test(ip);
async function geo(req:Request,ip:string|null){const cc=txt(req.headers.get('x-score-client-country')||req.headers.get('cf-ipcountry')||req.headers.get('x-vercel-ip-country'),2),region=txt(req.headers.get('x-score-client-region')||req.headers.get('x-vercel-ip-country-region'),16),city=txt(req.headers.get('x-score-client-city')||req.headers.get('x-vercel-ip-city'),160),tz=txt(req.headers.get('x-score-client-timezone')||req.headers.get('x-vercel-ip-timezone'),80);if(city)return{country_code:cc,region_code:region,city,ip_timezone:tz,geo_source:'edge_header',geo_resolved_at:new Date().toISOString()};if(!isPublicIp(ip))return{country_code:cc,region_code:region,city:null,ip_timezone:tz,geo_source:cc?'country_only':'unresolved',geo_resolved_at:null};try{const {data:c}=await db.rpc('ip_geo_cache_get',{p_ip:ip});const q=Array.isArray(c)?c[0]:c;if(q?.city)return{country_code:q.country_code||cc,region_code:q.region_code||region,city:q.city,ip_timezone:q.timezone||tz,geo_source:'ip_cache',geo_resolved_at:q.resolved_at||null};}catch{}
try{const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),1800);const r=await fetch(`https://ipwho.is/${encodeURIComponent(ip!)}`,{signal:ctl.signal,headers:{Accept:'application/json','User-Agent':'Score-Tracker-Geo/1.0'}});clearTimeout(timer);if(r.ok){const j=await r.json();if(j?.success&&j?.city){const z={country_code:txt(j.country_code,2)||cc,region_code:txt(j.region_code,16)||region,city:txt(j.city,160),ip_timezone:txt(typeof j.timezone==='string'?j.timezone:j.timezone?.id,80)||tz,geo_source:'ipwhois',geo_resolved_at:new Date().toISOString()};void db.rpc('ip_geo_cache_put',{p_ip:ip,p_country_code:z.country_code,p_region_code:z.region_code,p_city:z.city,p_timezone:z.ip_timezone,p_provider:'ipwho.is',p_ttl_days:30});return z}}}catch{}
return{country_code:cc,region_code:region,city:null,ip_timezone:tz,geo_source:cc?'country_only':'unresolved',geo_resolved_at:null}}
async function track(req:Request,body:any){const c=body.context||{},user=await auth(String(body.token||'')),ip=ipFrom(req),g=await geo(req,ip),row={event_id:uuid(c.eventId)||crypto.randomUUID(),session_id:uuid(c.sessionId),visitor_id:uuid(c.visitorId),event_type:txt(body.eventType,80)||'unknown',client_time:txt(c.clientTime,64),user_id:user?.id||null,ip_address:ip,...g,edge_region:txt(req.headers.get('x-vercel-id')||req.headers.get('cf-ray'),80),pathname:txt(c.pathname,300),app_page:txt(c.appPage,80),referrer_origin:txt(c.referrerOrigin,500),first_referrer:txt(c.firstReferrer,500),utm_source:txt(c.utmSource,160),utm_campaign:txt(c.utmCampaign,160),user_agent:txt(c.userAgent||req.headers.get('user-agent'),700),browser_language:txt(c.browserLanguage,40),client_timezone:txt(c.clientTimezone,80),screen_width:Number(c.screenWidth)||null,screen_height:Number(c.screenHeight)||null,viewport_width:Number(c.viewportWidth)||null,viewport_height:Number(c.viewportHeight)||null,account_mode:user?'account':'guest',is_pwa:!!c.isPwa,app_version:txt(c.appVersion,40),metadata:typeof body.metadata==='object'&&body.metadata?body.metadata:{}};const {error}=await db.from('score_tracker_visit_logs').insert(row);if(error&&error.code!=='23505')throw error;return{ok:true}}
async function snapshot(userId:string|null,visitorId:string|null){const now=Date.now(),since30=new Date(now-30*86400000).toISOString();let logs:any[]=[];if(userId){const r=await db.from('score_tracker_visit_logs').select('occurred_at,session_id,event_type,app_page').eq('user_id',userId);logs=r.data||[]}else if(visitorId){const r=await db.from('score_tracker_visit_logs').select('occurred_at,session_id,event_type,app_page').eq('visitor_id',visitorId);logs=r.data||[]}
const days=new Set(logs.map(x=>String(x.occurred_at).slice(0,10))),sessions=new Set(logs.map(x=>x.session_id).filter(Boolean)),l30=logs.filter(x=>x.occurred_at>=since30),days30=new Set(l30.map(x=>String(x.occurred_at).slice(0,10))),sessions30=new Set(l30.map(x=>x.session_id).filter(Boolean)),pages30=new Set(l30.map(x=>x.app_page).filter(Boolean));
let exams:any[]=[],scores:any[]=[];if(userId){const er=await db.from('score_tracker_exams').select('id,created_at').eq('user_id',userId),sr=await db.from('score_tracker_scores').select('exam_id,subject,target_score,actual_score').eq('user_id',userId);exams=er.data||[];scores=sr.data||[]}
const actualExam=new Set(scores.filter(x=>x.actual_score!==null).map(x=>x.exam_id)).size,targetExam=new Set(scores.filter(x=>x.target_score!==null).map(x=>x.exam_id)).size,subjectCoverage=new Set(scores.filter(x=>x.actual_score!==null||x.target_score!==null).map(x=>x.subject)).size;
const first=logs.length?logs.map(x=>new Date(x.occurred_at).getTime()).sort((a,b)=>a-b)[0]:null,last=logs.length?logs.map(x=>new Date(x.occurred_at).getTime()).sort((a,b)=>b-a)[0]:null,tenure=first?Math.max(0,Math.floor((now-first)/86400000)):0,edit=logs.filter(x=>x.event_type==='exam_updated').length,chart=logs.filter(x=>x.event_type==='chart_subject_changed').length,radar=logs.filter(x=>['radar_mode_changed','radar_exam_selected'].includes(x.event_type)).length;
const score=Math.min(100,Math.round(Math.min(20,days.size*3)+Math.min(15,sessions.size*1.5)+Math.min(20,exams.length*4)+Math.min(15,actualExam*4)+Math.min(10,subjectCoverage*1.2)+Math.min(10,(edit+chart+radar)*0.6)+Math.min(5,tenure/3)+Math.min(5,targetExam*1.5)));const level=score<15?'new':score<35?'casual':score<55?'returning':score<75?'engaged':'power';return{first_seen_at:first?new Date(first).toISOString():null,last_seen_at:last?new Date(last).toISOString():null,tenure_days:tenure,total_sessions:sessions.size,total_events:logs.length,total_active_days:days.size,sessions_30d:sessions30.size,events_30d:l30.length,active_days_30d:days30.size,unique_pages_30d:pages30.size,exam_count:exams.length,exams_with_actual:actualExam,exams_with_target:targetExam,score_row_count:scores.length,actual_score_count:scores.filter(x=>x.actual_score!==null).length,target_score_count:scores.filter(x=>x.target_score!==null).length,subject_coverage_count:subjectCoverage,exam_edit_events:edit,chart_interactions:chart,radar_interactions:radar,depth_score:score,depth_level:level,depth_calculated_at:new Date().toISOString()}}
async function saveFiles(feedbackId:string,replyId:string|null,userId:string|null,files:any[]){const rows=[];for(const f of (files||[]).slice(0,3)){const type=txt(f.type,80)||'application/octet-stream',name=(txt(f.name,120)||'image').replace(/[^\w.\-\u4e00-\u9fa5]/g,'_'),raw=typeof f.data==='string'?f.data.split(',').pop()||'':'';if(!raw||!type.startsWith('image/'))continue;const bytes=Uint8Array.from(atob(raw),c=>c.charCodeAt(0));if(bytes.length>5*1024*1024)continue;const path=`${feedbackId}/${replyId||'root'}/${crypto.randomUUID()}-${name}`;const up=await db.storage.from('score-tracker-feedback').upload(path,bytes,{contentType:type,upsert:false});if(up.error)throw up.error;rows.push({feedback_id:feedbackId,reply_id:replyId,uploaded_by:userId,storage_path:path,file_name:name,mime_type:type,size_bytes:bytes.length})}if(rows.length){const r=await db.from('score_tracker_feedback_attachments').insert(rows);if(r.error)throw r.error}}
async function feedbackRows(userId:string|null,guestHash:string|null){let q=db.from('score_tracker_feedback_submissions').select('id,feedback_type,content,status,created_at,depth_score,depth_level').order('created_at',{ascending:false});if(userId)q=q.eq('user_id',userId);else if(guestHash)q=q.eq('guest_access_hash',guestHash);else return[];const {data,error}=await q;if(error)throw error;const ids=(data||[]).map(x=>x.id);let replies:any[]=[];if(ids.length){const r=await db.from('score_tracker_feedback_replies').select('id,feedback_id,author_type,content,created_at,read_at').in('feedback_id',ids).order('created_at',{ascending:true});replies=r.data||[]}return(data||[]).map(x=>({...x,replies:replies.filter(r=>r.feedback_id===x.id),unread:replies.filter(r=>r.feedback_id===x.id&&r.author_type==='admin'&&!r.read_at).length}))}
async function signedAttachments(feedbackId:string){const {data}=await db.from('score_tracker_feedback_attachments').select('*').eq('feedback_id',feedbackId).order('created_at');const out=[];for(const a of data||[]){const s=await db.storage.from('score-tracker-feedback').createSignedUrl(a.storage_path,600);out.push({...a,url:s.data?.signedUrl||null})}return out}

Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return out({error:'Method not allowed'},405);try{const body=await req.json().catch(()=>({})),action=String(body.action??'');
if(action==='track_event')return out(await track(req,body));
if(action==='register'){let u='';for(let i=0;i<30;i++){const c=username(),{data}=await db.from('score_tracker_users').select('id').eq('username',c).maybeSingle();if(!data){u=c;break}}if(!u)throw new Error('暂时无法生成账号，请稍后重试');const p=password(),hp=await hashPassword(p),{data:user,error}=await db.from('score_tracker_users').insert({username:u,password_hash:hp.hash,password_salt:hp.salt}).select('id,username,is_admin').single();if(error)throw error;return out({user,password:p,token:await session(user.id),isNew:true})}
if(action==='login'){const u=String(body.username??'').trim().toLowerCase(),p=String(body.password??'');if(!u||!p)return out({error:'请输入用户名和密码'},400);const {data:user}=await db.from('score_tracker_users').select('id,username,password_hash,password_salt,is_admin').eq('username',u).maybeSingle();if(!user)return out({error:'用户名或密码不正确'},401);const hp=await hashPassword(p,unb64(user.password_salt));if(hp.hash!==user.password_hash)return out({error:'用户名或密码不正确'},401);return out({user:{id:user.id,username:user.username,is_admin:user.is_admin},token:await session(user.id),isNew:false})}
const user=await auth(String(body.token??''));
if(action==='feedback_submit'){const visitor=uuid(body.context?.visitorId),guest=txt(body.guestAccessToken,200),gh=!user&&guest?await sha(guest):null,content=txt(body.content,5000),type=txt(body.feedbackType,40)||'suggestion';if(!content)return out({error:'请填写反馈内容'},400);const snap=await snapshot(user?.id||null,visitor);const c=body.context||{};const {data:f,error}=await db.from('score_tracker_feedback_submissions').insert({feedback_type:type,content,user_id:user?.id||null,app_version:txt(c.appVersion,40),page_path:txt(c.pathname,300),user_agent:txt(c.userAgent,700),visitor_id:visitor,account_mode:user?'account':'guest',utm_source:txt(c.utmSource,160),utm_campaign:txt(c.utmCampaign,160),first_referrer:txt(c.firstReferrer,500),browser_language:txt(c.browserLanguage,40),client_timezone:txt(c.clientTimezone,80),is_pwa:!!c.isPwa,guest_access_hash:gh,...snap}).select('id').single();if(error)throw error;await saveFiles(f.id,null,user?.id||null,body.attachments||[]);return out({ok:true,id:f.id})}
if(action==='feedback_list'){const guest=txt(body.guestAccessToken,200),gh=!user&&guest?await sha(guest):null;return out({feedback:await feedbackRows(user?.id||null,gh)})}
if(action==='feedback_detail'){const id=uuid(body.feedbackId);if(!id)return out({error:'缺少反馈编号'},400);const guest=txt(body.guestAccessToken,200),gh=!user&&guest?await sha(guest):null;let q=db.from('score_tracker_feedback_submissions').select('*').eq('id',id);if(user)q=q.eq('user_id',user.id);else if(gh)q=q.eq('guest_access_hash',gh);else return out({error:'无权访问'},403);const {data:f}=await q.maybeSingle();if(!f)return out({error:'无权访问'},403);const {data:r}=await db.from('score_tracker_feedback_replies').select('*').eq('feedback_id',id).order('created_at');return out({feedback:f,replies:r||[],attachments:await signedAttachments(id)})}
if(action==='feedback_reply'){const id=uuid(body.feedbackId),content=txt(body.content,5000);if(!id||!content)return out({error:'请输入回复内容'},400);const guest=txt(body.guestAccessToken,200),gh=!user&&guest?await sha(guest):null;let q=db.from('score_tracker_feedback_submissions').select('id,user_id,guest_access_hash').eq('id',id);const {data:f}=await q.maybeSingle();if(!f||(!(user&&f.user_id===user.id)&&!(gh&&f.guest_access_hash===gh)))return out({error:'无权访问'},403);const {data:r,error}=await db.from('score_tracker_feedback_replies').insert({feedback_id:id,author_user_id:user?.id||null,author_type:'user',content}).select('id').single();if(error)throw error;await saveFiles(id,r.id,user?.id||null,body.attachments||[]);return out({ok:true,id:r.id})}
if(action==='feedback_mark_read'){const id=uuid(body.feedbackId);if(!id)return out({error:'缺少反馈编号'},400);const guest=txt(body.guestAccessToken,200),gh=!user&&guest?await sha(guest):null;const {data:f}=await db.from('score_tracker_feedback_submissions').select('user_id,guest_access_hash').eq('id',id).maybeSingle();if(!f||(!(user&&f.user_id===user.id)&&!(gh&&f.guest_access_hash===gh)))return out({error:'无权访问'},403);await db.from('score_tracker_feedback_replies').update({read_at:new Date().toISOString()}).eq('feedback_id',id).eq('author_type','admin').is('read_at',null);return out({ok:true})}
if(!user)return out({error:'登录已失效，请重新登录',code:'UNAUTHORIZED'},401);
if(action==='me')return out({user:{id:user.id,username:user.username,is_admin:user.is_admin}});
if(action==='logout'){await db.from('score_tracker_users').update({session_token_hash:null,session_expires_at:null}).eq('id',user.id);return out({ok:true})}
if(action==='list_exams'){const {data:exams,error}=await db.from('score_tracker_exams').select('id,name,exam_date,created_at,updated_at').eq('user_id',user.id).order('exam_date',{ascending:true}).order('created_at',{ascending:true});if(error)throw error;const ids=(exams??[]).map((e:any)=>e.id);let scores:any[]=[];if(ids.length){const r=await db.from('score_tracker_scores').select('id,exam_id,subject,target_score,actual_score,max_score').eq('user_id',user.id).in('exam_id',ids);if(r.error)throw r.error;scores=r.data??[]}return out({exams:(exams??[]).map((e:any)=>({...e,scores:Object.fromEntries(scores.filter(s=>s.exam_id===e.id).map(s=>[s.subject,{target:s.target_score===null?null:Number(s.target_score),actual:s.actual_score===null?null:Number(s.actual_score),max:Number(s.max_score??subjectMax[s.subject]??100)}]))}))})}
if(action==='save_exam'){const e=body.exam??{},name=String(e.name??'').trim().slice(0,60),date=String(e.exam_date??'');if(!name||!/^\d{4}-\d{2}-\d{2}$/.test(date))return out({error:'请填写考试名称和日期'},400);let id=String(e.id??''),created=!id;const now=new Date().toISOString();if(id){const {data}=await db.from('score_tracker_exams').select('id').eq('id',id).eq('user_id',user.id).maybeSingle();if(!data)return out({error:'没有找到这次考试'},404);let r=await db.from('score_tracker_exams').update({name,exam_date:date,updated_at:now}).eq('id',id).eq('user_id',user.id);if(r.error)throw r.error;r=await db.from('score_tracker_scores').delete().eq('exam_id',id).eq('user_id',user.id);if(r.error)throw r.error}else{const r=await db.from('score_tracker_exams').insert({user_id:user.id,name,exam_date:date}).select('id').single();if(r.error)throw r.error;id=r.data.id}const rows=subjects.map(subject=>{const s=e.scores?.[subject]??{};return{exam_id:id,user_id:user.id,subject,target_score:clean(s.target),actual_score:clean(s.actual),max_score:clean(s.max)??subjectMax[subject]??100,updated_at:now}}).filter(r=>r.target_score!==null||r.actual_score!==null);if(rows.length){const r=await db.from('score_tracker_scores').insert(rows);if(r.error)throw r.error}return out({ok:true,id,created})}
if(action==='delete_exam'){const id=String(body.examId??'');if(!id)return out({error:'缺少考试编号'},400);const {error}=await db.from('score_tracker_exams').delete().eq('id',id).eq('user_id',user.id);if(error)throw error;return out({ok:true})}
return out({error:'Unknown action'},400)}catch(e){console.error(e);return out({error:e instanceof Error?e.message:'服务器暂时开小差了'},500)}});