// v17 / product v1.1: direct position-percent input, statistical subtotal items, newest-first records.
state.rankEntryModeV17 = state.rankEntryModeV17 || 'rank';

(function injectV17Styles(){
  if (document.getElementById('app-v17-style')) return;
  var style=document.createElement('style');
  style.id='app-v17-style';
  style.textContent=`
    .rank-entry-mode-v17{display:flex;align-items:center;gap:7px;flex-wrap:wrap;margin:4px 0 10px}
    .rank-entry-mode-v17 .label{font-size:11px;font-weight:700;color:var(--muted)}
    .rank-entry-mode-v17 button{border:1px solid var(--line);background:#fff;color:#667085;border-radius:999px;padding:7px 11px;font-size:11px}
    .rank-entry-mode-v17 button.active{background:var(--text);border-color:var(--text);color:#fff;font-weight:700}
    .position-total-v17{display:none;margin-top:8px}
    .position-total-v17 label{display:block;font-size:10px;color:var(--muted);font-weight:700;margin-bottom:4px}
    .position-total-v17 input,.position-percent-v17{width:100%;min-width:0;border:1px solid var(--line);border-radius:10px;padding:9px 8px;background:#fff;outline:none}
    .position-percent-v17{display:none;grid-column:2/4}
    .rank-entry-percent-v17 .rank-scope-card-v16 .rank-pair-v16{display:none}
    .rank-entry-percent-v17 .position-total-v17{display:block}
    .rank-entry-percent-v17 .subject-rank-row-v16>input:not(.position-percent-v17){display:none}
    .rank-entry-percent-v17 .position-percent-v17{display:block}
    .exclude-total-v17{display:flex;align-items:center;gap:7px;margin:-2px 0 9px;font-size:11px;color:#667085;cursor:pointer;user-select:none}
    .exclude-total-v17 input{width:16px!important;height:16px;margin:0;accent-color:#5d72e8}
    .stat-badge-v17{display:inline-flex;align-items:center;border:1px solid #d9e3f3;background:#f4f7fb;color:#65758b;border-radius:999px;padding:2px 6px;font-size:9px;font-weight:700;margin-left:5px}
    .position-note-v17{font-size:10px;line-height:1.55;color:var(--muted);margin-top:7px}
    #app-version-v17{text-align:center;color:#a0a8b6;font-size:11px;padding:10px 12px calc(18px + env(safe-area-inset-bottom));letter-spacing:.03em}
    @media(max-width:620px){.rank-entry-mode-v17{display:grid;grid-template-columns:auto 1fr 1fr}.rank-entry-mode-v17 button{width:100%}.exclude-total-v17{margin-top:1px}}
  `;
  document.head.appendChild(style);
})();

(function addVersionFooterV17(){
  if (document.getElementById('app-version-v17')) return;
  var footer=document.createElement('footer');footer.id='app-version-v17';footer.textContent='Score Tracker · v1.1';document.body.appendChild(footer);
})();

function positionPerformanceV17(positionPercent){var p=num(positionPercent);if(p===null||p<0||p>100)return null;return Math.max(0,Math.min(100,100-p));}
var rankInfoByScopeBeforeV17=rankInfoByScopeV16;
rankInfoByScopeV16=function rankInfoByScopeV17(exam,subject,scope){if(!exam)return{rank:null,participants:null,performance:null,positionPercent:null,directPercent:false};var isClass=scope==='class';var direct=subject==='总分'?num(isClass?exam.total_class_position_percent:exam.total_year_position_percent):num(exam.scores?.[subject]?.[isClass?'classPositionPercent':'yearPositionPercent']);var base=rankInfoByScopeBeforeV17(exam,subject,scope);if(direct!==null&&direct>=0&&direct<=100)return{...base,performance:positionPerformanceV17(direct),positionPercent:direct,directPercent:true};return{...base,positionPercent:null,directPercent:false};};
rankInfoV7=function rankInfoV17(exam,subject){return rankInfoByScopeV16(exam,subject,state.rankScopeV16);};
rawRankValueV11=function rawRankValueV17(exam,subject){return rankInfoByScopeV16(exam,subject,state.rankScopeV16).rank;};

function totalSubjectsV17(exam){return Object.keys(exam?.scores||{}).filter(function(name){return !exam.scores?.[name]?.excludeFromTotal;});}
totalFor=function totalForV17(exam,key){var sum=0,count=0;totalSubjectsV17(exam).forEach(function(s){var v=examScore(exam,s,key);if(v!==null){sum+=v;count++;}});return count?sum:null;};
totalMax=function totalMaxV17(exam,key){var sum=0,count=0;totalSubjectsV17(exam).forEach(function(s){var v=examScore(exam,s,key);if(v!==null){sum+=examMax(exam,s);count++;}});return count?sum:null;};
totalRawForV13=function totalRawForV17(exam){var sum=0,count=0;totalSubjectsV17(exam).forEach(function(s){var v=examRawScoreV13(exam,s);if(v!==null){sum+=v;count++;}});return count?sum:null;};
totalRawMaxV13=function totalRawMaxV17(exam){var sum=0,count=0;totalSubjectsV17(exam).forEach(function(s){var v=examRawScoreV13(exam,s);if(v!==null){sum+=rawMaxV14(exam,s);count++;}});return count?sum:null;};
rawTotalFromRowsV13=function rawTotalFromRowsV17(rows){var sum=0,count=0;(rows||[]).forEach(function(row){if(row.excludeFromTotal)return;var raw=num(row.raw),actual=num(row.actual),v=raw??actual;if(v!==null){sum+=v;count++;}});return count?sum:null;};
finalTotalFromRowsV13=function finalTotalFromRowsV17(rows){var sum=0,count=0;(rows||[]).forEach(function(row){if(row.excludeFromTotal)return;var v=num(row.actual);if(v!==null){sum+=v;count++;}});return count?sum:null;};

function hasDirectPercentV17(scope){var isClass=scope==='class';return(state.exams||[]).some(function(exam){if(num(isClass?exam.total_class_position_percent:exam.total_year_position_percent)!==null)return true;return Object.values(exam.scores||{}).some(function(row){return num(row?.[isClass?'classPositionPercent':'yearPositionPercent'])!==null;});});}
function hasRawRankV17(scope){var isClass=scope==='class';return(state.exams||[]).some(function(exam){if(num(isClass?exam.total_class_rank:exam.total_rank)!==null)return true;return Object.values(exam.scores||{}).some(function(row){return num(row?.[isClass?'classRank':'rank'])!==null;});});}

var openExamBeforeV17=openExam;
openExam=function openExamV17(exam=null){
  openExamBeforeV17(exam);var modal=state.modal;if(!modal)return;
  var initial={};Object.entries(exam?.scores||{}).forEach(function(entry){var name=entry[0],row=entry[1]||{};initial[name]={excludeFromTotal:!!row.excludeFromTotal,yearPositionPercent:row.yearPositionPercent??'',classPositionPercent:row.classPositionPercent??''};});var customState={...initial};
  var directExists=num(exam?.total_year_position_percent)!==null||num(exam?.total_class_position_percent)!==null||Object.values(exam?.scores||{}).some(function(row){return num(row?.yearPositionPercent)!==null||num(row?.classPositionPercent)!==null;});var rankExists=num(exam?.total_rank)!==null||num(exam?.total_class_rank)!==null||Object.values(exam?.scores||{}).some(function(row){return num(row?.rank)!==null||num(row?.classRank)!==null;});var mode=directExists&&!rankExists?'percent':'rank';modal.dataset.rankEntryModeV17=mode;modal.classList.toggle('rank-entry-percent-v17',mode==='percent');
  var totalRanks=modal.querySelector('.total-ranks-v16');
  if(totalRanks&&!modal.querySelector('.rank-entry-mode-v17')){var switcher=document.createElement('div');switcher.className='rank-entry-mode-v17';switcher.innerHTML='<span class="label">录入方式</span><button type="button" data-entry-mode-v17="rank">名次</button><button type="button" data-entry-mode-v17="percent">位比</button>';totalRanks.parentNode.insertBefore(switcher,totalRanks);var cards=totalRanks.querySelectorAll('.rank-scope-card-v16');cards.forEach(function(card,index){var wrap=document.createElement('div');wrap.className='position-total-v17';var value=index===0?(exam?.total_year_position_percent??''):(exam?.total_class_position_percent??'');wrap.innerHTML='<label>位比（前 %）</label><input class="'+(index===0?'total-year-position-v17':'total-class-position-v17')+'" inputmode="decimal" value="'+escapeHtml(value)+'" placeholder="如 12.5">';card.appendChild(wrap);});var note=document.createElement('div');note.className='position-note-v17';note.textContent='位比按成绩单“前 x%”原样填写；趋势图会自动换算成越高越好的百分位。';totalRanks.insertAdjacentElement('afterend',note);}
  function snapshotCustom(){modal.querySelectorAll('.exam-subject-card-v10').forEach(function(card){var name=card.querySelector('.exam-subject-name-v10')?.value.trim();if(!name)return;customState[name]={excludeFromTotal:!!card.querySelector('.exclude-total-check-v17')?.checked,yearPositionPercent:card.querySelector('.year-position-v17')?.value??'',classPositionPercent:card.querySelector('.class-position-v17')?.value??''};});}
  function decorate(){modal.querySelectorAll('.exam-subject-card-v10').forEach(function(card){if(card.dataset.v17Decorated==='1')return;card.dataset.v17Decorated='1';var name=card.querySelector('.exam-subject-name-v10')?.value.trim()||'',saved=customState[name]||initial[name]||{excludeFromTotal:false,yearPositionPercent:'',classPositionPercent:''};var head=card.querySelector('.exam-subject-head-v10');if(head){var label=document.createElement('label');label.className='exclude-total-v17';label.innerHTML='<input type="checkbox" class="exclude-total-check-v17" '+(saved.excludeFromTotal?'checked':'')+'> <span>统计项，不计入总分</span>';head.insertAdjacentElement('afterend',label);}var rankRows=card.querySelectorAll('.subject-rank-row-v16');rankRows.forEach(function(row,index){var input=document.createElement('input');input.className='position-percent-v17 '+(index===0?'year-position-v17':'class-position-v17');input.inputMode='decimal';input.placeholder='位比（前%）';input.value=index===0?(saved.yearPositionPercent??''):(saved.classPositionPercent??'');row.appendChild(input);});});}
  function updateMode(){var current=modal.dataset.rankEntryModeV17||'rank';modal.classList.toggle('rank-entry-percent-v17',current==='percent');modal.querySelectorAll('[data-entry-mode-v17]').forEach(function(button){button.classList.toggle('active',button.dataset.entryModeV17===current);});}
  function updateTotals(){var rows=[...modal.querySelectorAll('.exam-subject-card-v10')].map(function(card){return{raw:card.querySelector('.raw-v16')?.value,actual:card.querySelector('.actual-v16')?.value,excludeFromTotal:!!card.querySelector('.exclude-total-check-v17')?.checked};});var rawEl=modal.querySelector('#rawTotalV16'),finalEl=modal.querySelector('#finalTotalV16');if(rawEl)rawEl.textContent=formatScore(rawTotalFromRowsV13(rows));if(finalEl)finalEl.textContent=formatScore(finalTotalFromRowsV13(rows));}
  decorate();updateMode();updateTotals();modal.querySelectorAll('[data-entry-mode-v17]').forEach(function(button){button.onclick=function(){snapshotCustom();modal.dataset.rankEntryModeV17=button.dataset.entryModeV17;updateMode();};});modal.addEventListener('input',function(){snapshotCustom();setTimeout(updateTotals,0);});modal.addEventListener('change',function(){snapshotCustom();setTimeout(updateTotals,0);});modal.addEventListener('click',function(event){if(event.target.closest('#addExamSubjectV16,.remove-exam-subject-v10'))snapshotCustom();},true);var observer=new MutationObserver(function(){decorate();updateMode();updateTotals();});var list=modal.querySelector('#examSubjectsV16');if(list)observer.observe(list,{childList:true,subtree:true});
};

var validateExamBeforeV17=validateExam;
validateExam=function validateExamV17(exam){var base=validateExamBeforeV17(exam);if(base)return base;function check(v,label){if(v===null||v===undefined||v==='')return'';var n=Number(v);return Number.isFinite(n)&&n>=0&&n<=100?'':label+'请输入 0～100';}var e=check(exam.total_year_position_percent,'年级位比');if(e)return e;e=check(exam.total_class_position_percent,'班级位比');if(e)return e;for(var entry of Object.entries(exam.scores||{})){var name=entry[0],row=entry[1]||{};e=check(row.yearPositionPercent,name+'年级位比');if(e)return e;e=check(row.classPositionPercent,name+'班级位比');if(e)return e;}return'';};

saveExam=async function saveExamV17(id,modal){var button=modal.querySelector('.save-btn'),mode=modal.dataset.rankEntryModeV17||'rank';var exam={id:id,name:modal.querySelector('#examName').value.trim(),exam_date:modal.querySelector('#examDate').value,grade_level:modal.querySelector('#gradeLevelV14')?.value||'',total_rank:mode==='rank'?(modal.querySelector('#totalRankV16')?.value||''):'',total_participants:mode==='rank'?(modal.querySelector('#totalParticipantsV16')?.value||''):'',total_class_rank:mode==='rank'?(modal.querySelector('#totalClassRankV16')?.value||''):'',total_class_participants:mode==='rank'?(modal.querySelector('#totalClassParticipantsV16')?.value||''):'',total_year_position_percent:mode==='percent'?(modal.querySelector('.total-year-position-v17')?.value||''):'',total_class_position_percent:mode==='percent'?(modal.querySelector('.total-class-position-v17')?.value||''):'',is_hidden:modal.querySelector('#examHiddenV16')?.value==='1',scores:{}};var seen=new Set();for(var card of modal.querySelectorAll('.exam-subject-card-v10')){var name=card.querySelector('.exam-subject-name-v10').value.trim();if(!name)return toast('请填写科目名称，或删除空白科目');if(seen.has(name))return toast(`科目「${name}」重复了`);seen.add(name);exam.scores[name]={target:card.querySelector('.target-v16')?.value||'',raw:card.querySelector('.raw-v16')?.value||'',actual:card.querySelector('.actual-v16')?.value||'',rawMax:card.querySelector('.rawmax-v16')?.value||'',max:card.querySelector('.max-v16')?.value||'',rank:mode==='rank'?(card.querySelector('.year-rank-v16')?.value||''):'',participants:mode==='rank'?(card.querySelector('.year-participants-v16')?.value||''):'',classRank:mode==='rank'?(card.querySelector('.class-rank-v16')?.value||''):'',classParticipants:mode==='rank'?(card.querySelector('.class-participants-v16')?.value||''):'',yearPositionPercent:mode==='percent'?(card.querySelector('.year-position-v17')?.value||''):'',classPositionPercent:mode==='percent'?(card.querySelector('.class-position-v17')?.value||''):'',excludeFromTotal:!!card.querySelector('.exclude-total-check-v17')?.checked};}if(!exam.name||!exam.exam_date)return toast('请填写考试名称和日期');var error=validateExam(exam);if(error)return toast(error);button.disabled=true;button.textContent='保存中…';try{await dataApiV7('save_exam',{exam:exam});await loadExams();modal.remove();state.modal=null;render();toast(id?'已保存修改':'考试已记录');}catch(e){toast(e.message);button.disabled=false;button.textContent=id?'保存修改':'保存考试';}};

recordHtml=function recordHtmlV17(exam){var subjects=Object.keys(exam.scores||{}),finalTotal=totalFor(exam,'actual'),rawTotal=totalRawForV13(exam);var tags=subjects.map(function(subject){var row=exam.scores[subject]||{},a=num(row.actual),raw=num(row.raw),t=num(row.target),year=rankInfoByScopeV16(exam,subject,'year'),cls=rankInfoByScopeV16(exam,subject,'class');if(a===null&&raw===null&&t===null&&year.rank===null&&year.positionPercent===null&&cls.rank===null&&cls.positionPercent===null)return'';var rankText='';if(year.directPercent)rankText+=` · 年位比 前${formatPercent(year.positionPercent)}`;else if(year.rank!==null)rankText+=` · 年排 ${year.rank}${year.participants?`/${year.participants}`:''}`;if(cls.directPercent)rankText+=` · 班位比 前${formatPercent(cls.positionPercent)}`;else if(cls.rank!==null)rankText+=` · 班排 ${cls.rank}${cls.participants?`/${cls.participants}`:''}`;return `<span class="score-tag">${escapeHtml(subject)}${row.excludeFromTotal?'<span class="stat-badge-v17">统计项</span>':''} ${a===null?'—':formatScore(a)}${raw!==null?`<span class="raw-final-inline-v13"> · 原始 <b>${formatScore(raw)}</b></span>`:''}<span style="color:#a1a9b5"> / 目标 ${t===null?'—':formatScore(t)}</span>${rankText?`<span style="color:#667085">${rankText}</span>`:''}</span>`;}).join('');var year=rankInfoByScopeV16(exam,'总分','year'),cls=rankInfoByScopeV16(exam,'总分','class'),badges='';if(year.directPercent)badges+=`<span class="score-tag"><b>年位比 前${formatPercent(year.positionPercent)}</b></span>`;else if(year.rank!==null)badges+=`<span class="score-tag"><b>年排 ${year.rank}${year.participants?` / ${year.participants}`:''}</b></span>`;if(cls.directPercent)badges+=`<span class="score-tag"><b>班位比 前${formatPercent(cls.positionPercent)}</b></span>`;else if(cls.rank!==null)badges+=`<span class="score-tag"><b>班排 ${cls.rank}${cls.participants?` / ${cls.participants}`:''}</b></span>`;return `<div class="record ${exam.is_hidden?'hidden-record-v10':''}"><div class="record-date">${fmtYearDate(exam.exam_date)}<b>${escapeHtml(exam.name)}<span class="grade-badge-v13">${escapeHtml(exam.grade_level||'未分类')}</span>${exam.is_hidden?'<span class="hidden-badge-v10">已隐藏</span>':''}</b></div><div class="record-scores">${tags||'<span class="score-tag">尚未填写分数或排名</span>'}<span class="score-tag"><b>赋分总分 ${finalTotal===null?'—':formatScore(finalTotal)}</b>${rawTotal!==null?` · 原始总分 ${formatScore(rawTotal)}`:''}</span>${badges}</div><div class="record-actions record-actions-v10"><button class="record-action-btn-v10" data-edit="${exam.id}">编辑</button><button class="record-action-btn-v10" data-hidden-toggle="${exam.id}">${exam.is_hidden?'恢复显示':'隐藏'}</button><button class="record-action-btn-v10 danger" data-delete="${exam.id}">删除</button></div></div>`;};

recordsHtml=function recordsHtmlV17(){var exams=state.allExams||[],hidden=exams.filter(function(e){return e.is_hidden;}).length,order=categoryOptionsV14();function recentFirst(a,b){var d=String(b.exam_date||'').localeCompare(String(a.exam_date||''));if(d)return d;return String(b.created_at||'').localeCompare(String(a.created_at||''));}var groups=[...order.map(function(v){return{name:v,exams:exams.filter(function(e){return e.grade_level===v;}).sort(recentFirst)};}),{name:'未分类',exams:exams.filter(function(e){return !e.grade_level;}).sort(recentFirst)}].filter(function(g){return g.exams.length;});return `<div class="page-head"><div><h2>考试记录</h2><p>按${escapeHtml(categoryLabelV14())}分组，每组按考试时间从近到远。${hidden?` ${hidden} 次已隐藏。`:''}</p></div><button class="primary" id="addExam">＋ 新建</button></div>${groups.length?groups.map(function(g){return `<section class="grade-section-v13"><div class="grade-section-head-v13"><h3>${escapeHtml(g.name)}</h3><span>${g.exams.length} 次</span></div><div class="card records-card">${g.exams.map(recordHtml).join('')}</div></section>`;}).join(''):`<div class="card records-card"><div class="empty-chart" style="height:260px"><div>还没有考试记录<br><button class="secondary" id="emptyAdd" style="margin-top:14px">记录第一场考试</button></div></div></div>`}`;};

var bindPageBeforeV17=bindPage;
bindPage=function bindPageV17(){bindPageBeforeV17();document.querySelectorAll('[data-trend-scope-v16]').forEach(function(button){button.onclick=function(){var scope=button.dataset.trendScopeV16;if(scope==='score'){state.trendMetric='score';}else{state.rankScopeV16=scope;if(hasDirectPercentV17(scope)&&!hasRawRankV17(scope))state.trendMetric='rank';else if(state.trendMetric!=='rank_raw'&&state.trendMetric!=='rank')state.trendMetric='rank_raw';}render();};});document.querySelectorAll('[data-radar-scope-v16]').forEach(function(button){button.onclick=function(){var scope=button.dataset.radarScopeV16;state.rankScopeV16=scope;if(hasDirectPercentV17(scope)&&!hasRawRankV17(scope))state.radarMode='rank';else if(state.radarMode!=='rank_raw'&&state.radarMode!=='rank')state.radarMode='rank_raw';state.radarSelection=[];ensureRadarSelection();render();};});};