import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const db=createClient(Deno.env.get('SUPABASE_URL')||'',Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'',{auth:{persistSession:false,autoRefreshToken:false}});
const H={'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-robots-tag':'noindex, nofollow, noarchive'};
const out=(v:any,status=200)=>new Response(JSON.stringify(v),{status,headers:H});
async function sha(v:string){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return[...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function auth(token:string){if(!token)return null;const {data,error}=await db.from('score_tracker_users').select('id,is_admin,session_expires_at').eq('session_token_hash',await sha(token)).maybeSingle();if(error)throw error;if(!data?.is_admin||!data.session_expires_at||new Date(data.session_expires_at).getTime()<Date.now())return null;return data}
function bytes(b64:string){const clean=b64.includes(',')?b64.slice(b64.indexOf(',')+1):b64;const raw=atob(clean);const a=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)a[i]=raw.charCodeAt(i);return a}
function ext(type:string){return type==='image/png'?'png':type==='image/webp'?'webp':type==='image/gif'?'gif':'jpg'}
Deno.serve(async req=>{if(req.method!=='POST')return out({error:'method_not_allowed'},405);try{const admin=await auth(req.headers.get('x-score-token')||'');if(!admin)return out({error:'unauthorized'},401);const b=await req.json().catch(()=>({})),id=String(b.id||''),content=String(b.content||'').trim().slice(0,5000),images=Array.isArray(b.images)?b.images.slice(0,3):[];if(!id||(!content&&!images.length))return out({error:'请输入回复内容或选择图片'},400);const owned=await db.from('score_tracker_feedback_submissions').select('id').eq('id',id).maybeSingle();if(owned.error)throw owned.error;if(!owned.data)return out({error:'feedback_not_found'},404);const rr=await db.from('score_tracker_feedback_replies').insert({feedback_id:id,author_user_id:admin.id,author_type:'admin',content}).select('id,created_at').single();if(rr.error)throw rr.error;const replyId=rr.data.id,attachments:any[]=[];
 for(let i=0;i<images.length;i++){const x=images[i]||{},type=String(x.mime_type||x.type||'image/jpeg');if(!['image/png','image/jpeg','image/webp','image/gif'].includes(type))continue;const data=bytes(String(x.data||''));if(!data.length||data.length>2*1024*1024)continue;const path=`${id}/admin/${replyId}/${crypto.randomUUID()}.${ext(type)}`;const up=await db.storage.from('score-tracker-feedback').upload(path,data,{contentType:type,upsert:false});if(up.error)throw up.error;const ar=await db.from('score_tracker_feedback_attachments').insert({feedback_id:id,reply_id:replyId,uploaded_by:admin.id,storage_path:path,file_name:String(x.name||`reply-${i+1}.${ext(type)}`).slice(0,180),mime_type:type,size_bytes:data.length}).select('id,storage_path,mime_type,file_name,size_bytes').single();if(ar.error)throw ar.error;const su=await db.storage.from('score-tracker-feedback').createSignedUrl(path,900);attachments.push({...ar.data,url:su.data?.signedUrl||null});}
 await db.from('score_tracker_feedback_submissions').update({status:'reviewing'}).eq('id',id).eq('status','new');return out({ok:true,reply:{id:replyId,created_at:rr.data.created_at,content,attachments}})}catch(e){console.error(e);return out({error:e instanceof Error?e.message:'reply_failed'},500)}});
